LOG:  database system was shut down at 2014-05-22 09:09:12 EDT
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
FATAL:  database "homework_app_development" does not exist
ERROR:  relation "cohorts" already exists
STATEMENT:  CREATE TABLE "cohorts" ("id" serial primary key, "start_date" date, "user_id" integer, "course_id" integer) 
ERROR:  relation "cohorts" already exists
STATEMENT:  CREATE TABLE "cohorts" ("id" serial primary key, "start_date" date, "user_id" integer, "course_id" integer) 
ERROR:  relation "cohorts" already exists
STATEMENT:  CREATE TABLE "cohorts" ("id" serial primary key, "start_date" date, "course_id" integer, "location_id" integer) 
ERROR:  relation "cohorts" already exists
STATEMENT:  CREATE TABLE "cohorts" ("id" serial primary key, "start_date" date, "course_id" integer, "location_id" integer) 
ERROR:  relation "cohorts" already exists
STATEMENT:  CREATE TABLE "cohorts" ("id" serial primary key, "start_date" date, "location_id" integer, "course_id" integer) 
ERROR:  relation "sessions" does not exist at character 323
STATEMENT:                SELECT a.attname, format_type(a.atttypid, a.atttypmod),
	                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
	                FROM pg_attribute a LEFT JOIN pg_attrdef d
	                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
	               WHERE a.attrelid = '"sessions"'::regclass
	                 AND a.attnum > 0 AND NOT a.attisdropped
	               ORDER BY a.attnum
	
LOG:  database system was shut down at 2014-05-31 18:31:55 EDT
LOG:  database system is ready to accept connections
LOG:  autovacuum launcher started
ERROR:  column users.cohort_id does not exist at character 38
STATEMENT:  SELECT "users".* FROM "users"  WHERE "users"."cohort_id" = 2
